### ISSUE TITLE
iOS真机搜索设备不成功，模拟器正常投屏

### ISSUE THREAD

**Issue by figbin** [515445681/flutter_dlna#4]
flutter: ios dlna start search  就没有反应了。
试了 iPhone6 Plus iOS 12.4.8 以及 iPhone SE2 iOS 14.2
均失败。

**Comment by 515445681** [comment]
在电视或者安卓机上装个乐播投屏试试，我这边在乐播下测的很稳定

**Comment by figbin** [comment]
> 在电视或者安卓机上装个乐播投屏试试，我这边在乐播下测的很稳定

谢谢作者提供这么好的插件，但我电视机上有 乐播投屏，并且我已经打开了 乐播软件。
创维的电视，不知道是什么原因，两台手机均无法发现设备。还试了一台康佳的电视，也无法发现，也许是MRDLNA的问题
安卓手机和苹果模拟器都挺好的。

**Comment by 515445681** [comment]
网络环境呢，手机连接的网络是不是跟电视所在网络不是同一个路由器。跨路由器通信了。

**Comment by figbin** [comment]
同一个路由器的～目前仍找不到原因，搞不好苹果设备是不是有什么防火墙之类。

**Comment by 515445681** [comment]
没有的，xcode调试看看错误信息吧。
